on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
    - main
    paths:
    - src/**
    - .github/workflows/check_taxon_info.yaml
  workflow_dispatch:
    branches: [ main ]


name: match easin to gbif backbone

jobs:
  mapping:
    runs-on: ubuntu-latest

    name: ubuntu-latest (R release)

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get branch name
        run: |
          git branch --show-current
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install linux libraries
        run: |
          sudo apt install libsodium-dev
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libgdal-dev libproj-dev
          sudo apt install libudunits2-dev
      
      - name: Install remotes package
        run: Rscript -e 'install.packages("remotes")'

      - name: Install dependencies for parallel computing
        run: Rscript -e 'install.packages(c("carrier", "mirai"))'

      - name: Install R packages
        run: |
          source("src/install_packages.R")
        shell: Rscript {0}

      - name: Match EASIN catalogue to GBIF Backbone
        run: |
          source("src/match_easin_catalogue.R")
        shell: Rscript {0}

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO]"
          commit_message: "Map EASIN catalogue to GBIF Backbone"
          target_branch: automatic-update
          add_timestamp: true

      - name: Run tests
        run: |
          source("tests/test_output_match.R")
        shell: Rscript {0}
      
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          title: "[AUTO] Update data"
          template: .github/PULL_REQUEST_TEMPLATE.md
          reviewer: damianooldoni
          label: automated workflow
          get_diff: false
